DROP PROCEDURE IF EXISTS school.SP_USERTREEVIEW;
CREATE PROCEDURE school.SP_USERTREEVIEW()
BEGIN
  
  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL, TREEVIEW_ORDER
  FROM USERTREEVIEW
  ORDER BY TREEVIEW_LEVEL, TREEVIEW_ORDER;
  
/*
	SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL
  FROM TREEVIEW
  WHERE TREEVIEW_ISACTIVE = 1
  AND TREEVIEW_LEVEL = 0;

  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL
  FROM TREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_HOME')
  AND TREEVIEW_ISACTIVE = 1;

  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL
  FROM TREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_EMPLOYEE')
  AND TREEVIEW_ISACTIVE = 1
  ORDER BY TREEVIEW_LEVEL;

  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL
  FROM TREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_EMPLOYER')
  AND TREEVIEW_ISACTIVE = 1
  ORDER BY TREEVIEW_LEVEL;
  
  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL
  FROM TREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_ADMIN')
  AND TREEVIEW_ISACTIVE = 1
  UNION
  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL
  FROM TREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_ADDADMIN')
  AND TREEVIEW_ISACTIVE = 1
  ORDER BY TREEVIEW_LEVEL;
*/  
  
END;
