DROP TABLE IF EXISTS school.USERTREEVIEW;

CREATE TABLE school.USERTREEVIEW (
  `TreeView_ID` varchar(30) NOT NULL,
  `TreeView_ParentID` varchar(30) DEFAULT NULL,
  `TreeView_Desc` varchar(30) DEFAULT NULL,
  `TreeView_URL` longtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `TreeView_Level` int DEFAULT NULL,
  `TreeView_ORDER` int DEFAULT NULL,
  `TreeView_IsActive` int DEFAULT NULL,
  PRIMARY KEY (`TreeView_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


TRUNCATE TABLE USERTREEVIEW;

INSERT INTO USERTREEVIEW VALUES('TREEVIEW_HOME', NULL, 'Home', '#', 0, 1, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_ABOUT', 'TREEVIEW_HOME', 'About', '#', 1, 1, 1);

INSERT INTO USERTREEVIEW VALUES('TREEVIEW_EMPLOYEE', NULL, 'Employee', '#', 0, 2, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_UPLOADRESUME', 'TREEVIEW_EMPLOYEE', 'Upload Resume', '#', 1, 1, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_EDITRESUME', 'TREEVIEW_EMPLOYEE' , 'Edit Resume', '#', 1, 2, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_VIEWRESUME', 'TREEVIEW_EMPLOYEE' , 'View Resume', '#', 1, 3, 1);

INSERT INTO USERTREEVIEW VALUES('TREEVIEW_EMPLOYER', NULL, 'Employer', '#', 0, 3, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_UPLOADJOB', 'TREEVIEW_EMPLOYER', 'Upload Job', '#', 1, 1, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_EDITJOB', 'TREEVIEW_EMPLOYER' , 'Edit Job', '#', 1, 2, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_VIEWJOB', 'TREEVIEW_EMPLOYER' , 'View Job', '#', 1, 3, 1);

INSERT INTO USERTREEVIEW VALUES('TREEVIEW_ADMIN', NULL, 'Admin', '#', 0, 4, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_USER', 'TREEVIEW_ADMIN', 'User', '#', 1, 1, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_ADDUSER', 'TREEVIEW_USER' , 'Add User', '#', 2, 1, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_EDITUSER', 'TREEVIEW_USER', 'Edit User', '#', 2, 2, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_REMOVEUSER', 'TREEVIEW_USER', 'Remove User', '#', 2, 3, 1);
INSERT INTO USERTREEVIEW VALUES('TREEVIEW_VIEWUSER', 'TREEVIEW_ADMIN' , 'View User', '#', 1, 2, 1);

CALL SP_USERTREEVIEW();

  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL, TREEVIEW_ORDER
  FROM USERTREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_ADMIN')
  AND TREEVIEW_ISACTIVE = 1
  UNION
  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL, TREEVIEW_ORDER
  FROM USERTREEVIEW
  WHERE TREEVIEW_PARENTID = TRIM('TREEVIEW_USER')
  AND TREEVIEW_ISACTIVE = 1
  ORDER BY TREEVIEW_ORDER;
  
  SELECT TREEVIEW_ID, TREEVIEW_PARENTID, TREEVIEW_DESC, TREEVIEW_URL, TREEVIEW_LEVEL, TREEVIEW_ORDER
  FROM USERTREEVIEW
  ORDER BY TREEVIEW_LEVEL, TREEVIEW_ORDER;