DROP TABLE IF EXISTS school.USERMENU;

CREATE TABLE school.USERMENU (
  `Menu_ID` varchar(20) NOT NULL,
  `Menu_ParentID` varchar(20) DEFAULT NULL,
  `Menu_Desc` varchar(30) DEFAULT NULL,
  `Menu_URL` longtext CHARACTER SET latin1 COLLATE latin1_swedish_ci,
  `Menu_Level` int DEFAULT NULL,
  `Menu_IsActive` int DEFAULT NULL,
  PRIMARY KEY (`Menu_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO USERMENU VALUES('MENU_HOME', NULL, 'Home', 'Default.aspx', 0, 1);
INSERT INTO USERMENU VALUES('MENU_ABOUT', 'MENU_HOME', 'About', 'About.aspx', 1, 1);
INSERT INTO USERMENU VALUES('MENU_HELP', 'MENU_HOME', 'Help', '#', 2, 1);
INSERT INTO USERMENU VALUES('MENU_UPDATE', 'MENU_HELP', 'Update', '#', 3, 1);

INSERT INTO USERMENU VALUES('MENU_MANAGEFILES', NULL, 'Manage Files', '#', 0, 1);
INSERT INTO USERMENU VALUES('MENU_FILEUPLOAD', 'MENU_MANAGEFILES', 'Upload File', 'FileUpload.aspx', 1, 1);
INSERT INTO USERMENU VALUES('MENU_FILERETRIEVE', 'MENU_MANAGEFILES', 'Retrieve File', 'FileRetrieve.aspx', 2, 1);
INSERT INTO USERMENU VALUES('MENU_FILESAVE', 'MENU_FILERETRIEVE', 'Save File', '#', 2, 1);

INSERT INTO USERMENU VALUES('MENU_VIEWDATA', NULL, 'View Data', '#', 0, 1);
INSERT INTO USERMENU VALUES('MENU_LOADDATA', 'MENU_VIEWDATA', 'Load Data', '#', 1, 1);
INSERT INTO USERMENU VALUES('MENU_GRIDVIEW', 'MENU_VIEWDATA', 'Grid View', 'GridView.aspx', 2, 1);

CALL SP_USERMENU();
SELECT * FROM school.USERMENU;

SELECT MENU_ID, MENU_PARENTID, MENU_DESC, MENU_URL, MENU_LEVEL
FROM USERMENU
ORDER BY MENU_LEVEL;


SELECT MENU_ID, MENU_PARENTID, MENU_DESC, MENU_URL, MENU_ORDER
FROM USERMENU
WHERE MENU_PARENTID = TRIM('MENU_HOME')
AND MENU_ISACTIVE = 1
UNION
SELECT MENU_ID, MENU_PARENTID, MENU_DESC, MENU_URL, MENU_ORDER
FROM USERMENU
WHERE MENU_PARENTID = TRIM('MENU_HELP')
AND MENU_ISACTIVE = 1
ORDER BY MENU_ORDER;
